# datos proyecto catálogo
/* 20 datos tabla marcas */
INSERT INTO marcas
    (marca)
VALUES
    ('Apple'),
    ('Samsung'),
    ('Sony'),
    ('LG'),
    ('Philips'),
    ('JBL'),
    ('Bose'),
    ('Xiaomi'),
    ('Motorola'),
    ('HP'),
    ('Dell'),
    ('Lenovo'),
    ('Asus'),
    ('Logitech'),
    ('Anker'),
    ('Sennheiser'),
    ('Pioneer'),
    ('Harman Kardon'),
    ('Marshall'),
    ('Epson');

/* 20 datos tabla categorías */
INSERT INTO categorias
    (categoria)
VALUES
    ('Smartphones'),
    ('Notebooks'),
    ('Tablets'),
    ('Auriculares'),
    ('Parlantes'),
    ('Televisores'),
    ('Monitores'),
    ('Impresoras'),
    ('Accesorios Apple'),
    ('Cargadores y Cables'),
    ('Teclados y Mouse'),
    ('Almacenamiento'),
    ('Cámaras'),
    ('Home Theater'),
    ('Smartwatches'),
    ('Consolas'),
    ('Proyectores'),
    ('Aires Acondicionados'),
    ('Wearables'),
    ('Reproductores de Audio');

/* 50 datos tabla productos */
INSERT INTO productos
    (producto, precio, idMarca, idCategoria, descripcion, imagen, activo)
VALUES

    ('iPhone 15 128GB Negro',                1133.50,  1,  1,  'Smartphone Apple con chip A16 Bionic, pantalla Super Retina XDR 6.1", cámara de 48MP y batería de larga duración.',                           'iphone15_negro.jpg',       1),
    ('iPhone 15 Pro 256GB Titanio',          1533.50,  1,  1,  'Smartphone Apple con chip A17 Pro, pantalla ProMotion 120Hz, sistema de cámaras Pro de 48MP y diseño en titanio.',                            'iphone15pro_titanio.jpg',  1),
    ('MacBook Air M2 8GB 256GB',             1666.50,  1,  2,  'Notebook ultradelgada con chip Apple M2, pantalla Liquid Retina 13.6", hasta 18 horas de batería y diseño fanless.',                          'macbook_air_m2.jpg',       1),
    ('MacBook Pro M3 16GB 512GB',            2600.00,  1,  2,  'Notebook profesional con chip Apple M3, pantalla Liquid Retina XDR 14", GPU de 10 núcleos y conectividad Thunderbolt 4.',                     'macbook_pro_m3.jpg',       1),
    ('iPad Air 11" M2 64GB WiFi',            866.50,  1,  3,  'Tablet Apple con chip M2, pantalla Liquid Retina 11", compatible con Apple Pencil y Magic Keyboard, ideal para productividad.',               'ipad_air_m2.jpg',          1),
    ('Apple Watch Series 9 45mm',             600.00,  1, 15,  'Smartwatch con chip S9, pantalla Always-On Retina, monitoreo de salud avanzado, GPS y resistencia al agua WR50.',                            'applewatch_s9.jpg',        1),
    ('AirPods Pro 2da Generación',            433.50,  1,  4,  'Auriculares inalámbricos Apple con cancelación activa de ruido, modo Transparencia, audio espacial y estuche con MagSafe.',                   'airpods_pro2.jpg',         1),
    ('Samsung Galaxy S24 256GB',             1000.00,  2,  1,  'Smartphone Samsung con procesador Snapdragon 8 Gen 3, pantalla Dynamic AMOLED 6.2" 120Hz y sistema de cámaras con IA.',                      'galaxy_s24.jpg',           1),
    ('Samsung Galaxy Tab S9 128GB',           666.50,  2,  3,  'Tablet Samsung con pantalla AMOLED 11" 120Hz, procesador Snapdragon 8 Gen 2, resistencia IP68 y stylus S Pen incluido.',                     'galaxy_tab_s9.jpg',        1),
    ('Samsung Smart TV 55" QLED 4K',         800.00,  2,  6,  'Televisor QLED 4K con procesador Neural Quantum, Quantum HDR, sistema operativo Tizen y compatibilidad con Alexa y Google.',                  'samsung_tv_55.jpg',        1),
    ('Sony WH-1000XM5',                       466.50,  3,  4,  'Auriculares over-ear con la mejor cancelación de ruido de Sony, 30 horas de batería, carga rápida y sonido Hi-Res Audio.',                   'sony_wh1000xm5.jpg',       1),
    ('Sony WF-1000XM5',                       333.50,  3,  4,  'Auriculares in-ear true wireless con cancelación de ruido líder en la industria, hasta 36 horas de autonomía total.',                        'sony_wf1000xm5.jpg',       1),
    ('Sony Bravia XR 65" OLED 4K',           1866.50,  3,  6,  'Televisor OLED 4K con procesador cognitivo XR, XR OLED Contrast, Google TV integrado y compatibilidad con Dolby Vision.',                   'sony_bravia_65.jpg',       1),
    ('LG OLED 55" C3 4K',                   1466.50,  4,  6,  'Televisor OLED evo 4K con procesador α9 Gen6, Dolby Vision IQ, G-Sync compatible y 4 puertos HDMI 2.1 para gaming.',                         'lg_oled55_c3.jpg',         1),
    ('LG Monitor 27" UltraFine 4K',           500.00,  4,  7,  'Monitor 4K IPS de 27" con calibración de fábrica, compatibilidad Thunderbolt 3, brillo de 500 nits y cubierta antirreflejo.',               'lg_ultrafine_27.jpg',      1),
    ('Philips Hue Starter Kit',               200.00,  5, 10,  'Kit de iluminación inteligente con 3 bombillas A19, puente Hue y compatibilidad con Alexa, Google Assistant y Apple HomeKit.',              'philips_hue_kit.jpg',      1),
    ('JBL Charge 5',                          200.00,  6,  5,  'Parlante Bluetooth portátil resistente al agua IP67, 20 horas de reproducción, PowerBank integrado y sonido potente con graves profundos.',  'jbl_charge5.jpg',          1),
    ('JBL Flip 6',                            126.50,  6,  5,  'Parlante Bluetooth portátil con resistencia IP67, 12 horas de batería, sonido JBL Pro con dos tweeter y un woofer.',                        'jbl_flip6.jpg',            1),
    ('JBL Tune 770NC',                        166.50,  6,  4,  'Auriculares over-ear inalámbricos con cancelación de ruido adaptativa, hasta 70 horas de batería y carga rápida.',                          'jbl_tune770nc.jpg',        1),
    ('Bose QuietComfort 45',                  433.50,  7,  4,  'Auriculares over-ear con cancelación de ruido Bose, 24 horas de autonomía, modo Aware y diseño plegable para viajes.',                      'bose_qc45.jpg',            1),
    ('Bose SoundLink Flex',                   233.50,  7,  5,  'Parlante Bluetooth portátil con diseño resistente al agua IP67, sonido posicionado para exteriores y 12 horas de batería.',                  'bose_soundlink_flex.jpg',  1),
    ('Xiaomi Redmi Note 13 128GB',            286.50,  8,  1,  'Smartphone con pantalla AMOLED 6.67" 120Hz, cámara de 108MP, batería de 5000mAh y carga rápida de 33W.',                                    'redmi_note13.jpg',         1),
    ('Xiaomi Mi Band 8',                       60.00,  8, 19,  'Pulsera inteligente con pantalla AMOLED 1.62", monitoreo de salud 24/7, GPS asistido, 16 días de autonomía y resistencia 5ATM.',            'mi_band8.jpg',             1),
    ('Motorola Edge 40 256GB',                466.50,  9,  1,  'Smartphone con pantalla pOLED 6.55" 144Hz, cámara de 50MP con OIS, carga TurboPower 68W y diseño resistente al agua IP68.',                 'moto_edge40.jpg',          1),
    ('Motorola Moto G84 256GB',               253.50,  9,  1,  'Smartphone con pantalla pOLED 6.55" 120Hz, cámara de 50MP, batería de 5000mAh con carga de 33W y altavoz estéreo Dolby Atmos.',             'moto_g84.jpg',             1),
    ('HP Victus 15 Ryzen 5 16GB 512GB',      800.00, 10,  2,  'Notebook gaming con AMD Ryzen 5 7535HS, GPU NVIDIA RTX 2050, pantalla FHD 144Hz y sistema de enfriamiento térmico optimizado.',             'hp_victus15.jpg',          1),
    ('HP LaserJet Pro M404dn',                400.00, 10,  8,  'Impresora láser monocromática con impresión dúplex automática, hasta 40 ppm, conectividad Ethernet y USB, ideal para oficina.',             'hp_laserjet_m404.jpg',     1),
    ('Dell XPS 15 i7 32GB 1TB',              2200.00, 11,  2,  'Notebook premium con Intel Core i7-13700H, GPU NVIDIA RTX 4060, pantalla OLED 3.5K táctil y batería de 86Wh.',                             'dell_xps15.jpg',           1),
    ('Dell Monitor S2722QC 27" 4K',           366.50, 11,  7,  'Monitor 4K IPS de 27" con USB-C 65W, dos puertos HDMI, DisplayPort, hub USB integrado y compatibilidad con HDR400.',                       'dell_s2722qc.jpg',         1),
    ('Lenovo IdeaPad 5 i5 8GB 512GB',         600.00, 12,  2,  'Notebook con Intel Core i5-1335U, pantalla IPS FHD 15.6", WiFi 6, lector de huellas digitales y batería de hasta 12 horas.',               'lenovo_ideapad5.jpg',      1),
    ('Lenovo Tab P12 256GB',                  500.00, 12,  3,  'Tablet con pantalla IPS 12.7" 3K, procesador MediaTek Dimensity 7050, 8GB de RAM, cuatro altavoces JBL y stylus incluido.',                 'lenovo_tab_p12.jpg',       1),
    ('Asus ROG Zephyrus G14 RTX 4060',       1933.50, 13,  2,  'Notebook gaming con AMD Ryzen 9 8945HS, RTX 4060, pantalla OLED 2.8K 120Hz y diseño ultracompacto de 14" para gaming profesional.',        'asus_rog_g14.jpg',         1),
    ('Asus ProArt PA279CRV 27" 4K',           600.00, 13,  7,  'Monitor profesional 4K IPS con cobertura 100% sRGB y 99% DCI-P3, calibración de fábrica Delta E<2 y USB-C 96W.',                           'asus_proart_pa279.jpg',    1),
    ('Logitech MX Master 3S',                 133.50, 14, 11,  'Mouse inalámbrico premium con sensor de 8000 DPI, rueda de desplazamiento MagSpeed, ergonomía avanzada y conexión Bolt o Bluetooth.',       'logitech_mx_master3s.jpg', 1),
    ('Logitech MX Keys S',                    166.50, 14, 11,  'Teclado inalámbrico full-size con teclas de perfil perfecto, retroiluminación adaptativa, conexión multi-dispositivo y batería de 10 días.', 'logitech_mx_keys_s.jpg',   1),
    ('Logitech G Pro X Superlight 2',         200.00, 14, 11,  'Mouse gaming ultraliviano de 60g con sensor HERO 2 25K, hasta 95 horas de batería, botones con efecto Hall y diseño simétrico.',            'logitech_gpro_sl2.jpg',    1),
    ('Anker PowerCore 26800mAh',              100.00, 15, 10,  'Batería portátil de alta capacidad con dos puertos USB-A y un USB-C, carga rápida de 18W y tecnología PowerIQ 3.0.',                       'anker_powercore26800.jpg', 1),
    ('Anker Cable USB-C a Lightning MFi 1m',   20.00, 15, 10,  'Cable certificado MFi de 1 metro con conector USB-C, compatible con carga rápida Power Delivery hasta 30W para dispositivos Apple.',        'anker_cable_cl.jpg',       1),
    ('Anker 737 Cargador 120W GaN',           86.50, 15, 10,  'Cargador compacto GaN de 120W con tres puertos (2x USB-C y 1x USB-A), ideal para cargar notebook, tablet y smartphone simultáneamente.',   'anker_737_gan.jpg',        1),
    ('Sennheiser HD 560S',                    300.00, 16,  4,  'Auriculares over-ear abiertos con respuesta en frecuencia extendida hasta 38kHz, Hi-Res Audio, diseño cómodo para largas sesiones.',       'sennheiser_hd560s.jpg',    1),
    ('Sennheiser Momentum 4 Wireless',        466.50, 16,  4,  'Auriculares inalámbricos premium con cancelación de ruido adaptativa, 60 horas de autonomía, sonido Sennheiser Signature y Bluetooth 5.2.','sennheiser_momentum4.jpg', 1),
    ('Pioneer DJ DDJ-400',                    466.50, 17, 20,  'Controlador DJ de 2 canales para rekordbox, con jog wheels de 6", efectos Beat FX y Pad FX, ideal para principiantes y nivel intermedio.',  'pioneer_ddj400.jpg',       1),
    ('Pioneer Stereo A-10',                   400.00, 17, 14,  'Amplificador estéreo de 50W x2 con entradas analógicas y digitales, filtro de audio Direct Energy HD y modo A/B de operación.',            'pioneer_a10.jpg',          1),
    ('Harman Kardon Onyx Studio 8',           366.50, 18,  5,  'Parlante Bluetooth portátil con diseño premium, 8 horas de autonomía, luz LED ambiental, resistencia IPX5 y sonido envolvente 360°.',      'harman_onyx8.jpg',         1),
    ('Marshall Emberton III',                 200.00, 19,  5,  'Parlante Bluetooth portátil con estética clásica Marshall, 30 horas de reproducción, resistencia IP67 y sonido estéreo verdadero.',         'marshall_emberton3.jpg',   1),
    ('Marshall Acton III',                    533.50, 19,  5,  'Parlante de estante con WiFi, Bluetooth y entrada analógica, tres amplificadores de clase D, tweeter de cúpula y diseño icónico Marshall.', 'marshall_acton3.jpg',      1),
    ('Epson EcoTank L3250',                   233.50, 20,  8,  'Impresora multifunción tinta con sistema de tanque recargable, impresión, copia y escaneo, WiFi, compatible con Epson Connect y Alexa.',    'epson_l3250.jpg',          1),
    ('Epson EF-21 Mini Proyector',            466.50, 20, 17,  'Miniproyector láser Android TV con brillo de 1000 lúmenes, resolución Full HD, altavoz integrado de 5W y autonomía de hasta 2.5 horas.',  'epson_ef21.jpg',           1),
    ('Apple Magic Keyboard Touch ID ES',      200.00,  1,  9,  'Teclado inalámbrico Apple con Touch ID integrado, diseño ultradelgado, batería recargable de larga duración y layout en español.',          'apple_magic_kb.jpg',       1),
    ('Apple MagSafe Charger 2m',              53.50,  1,  9,  'Cargador MagSafe oficial de Apple con cable de 2 metros, carga magnética de hasta 15W para iPhone 12 o superior y AirPods con estuche MagSafe.','apple_magsafe_2m.jpg', 1);